<?php
// Generated by ZF2's ./bin/classmap_generator.php
return array(
  'Db\ActiveRecord'                            => __DIR__ . '/ActiveRecord.php',
  'Db\Exception\VarientDatabaseException'      => __DIR__ . '/Exception/VarientDatabaseException.php',
  'Db\Exception\ExceptionInterface'            => __DIR__ . '/Exception/ExceptionInterface.php',
  'Db\Exception\ModelNotFoundException'        => __DIR__ . '/Exception/ModelNotFoundException.php',
  'Db\Exception\TablePrimaryNotFoundException' => __DIR__ . '/Exception/TablePrimaryNotFoundException.php',
  'Db\Exception\UnknownCallableException'      => __DIR__ . '/Exception/UnknownCallableException.php',
  'Db\AbstractTable'                           => __DIR__ . '/AbstractTable.php',
  'Db\Helper\TableLoader'                      => __DIR__ . '/Helper/TableLoader.php',
  'Db\AbstractModel'                           => __DIR__ . '/AbstractModel.php',
);
